INTEX/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace INTEX.Models
{
    [Table("Customer")]
    public class Customer
    {
        [Key]
        public int CustomerID { get; set; }

        [Required(ErrorMessage = "Please enter your first name")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter your last name")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Address")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Please enter your city")]
        [Display(Name = " City")]
        public string City { get; set; }

        [Required(ErrorMessage = "Please enter your state")]
        [Display(Name = "State")]
        public string State { get; set; }

        [Required(ErrorMessage = "Please enter your zip code")]
        [Display(Name = "Zip Code")]
        [StringLength(5, MinimumLength = 5, ErrorMessage = "Zip should be 5 digits")]
        public string Zip { get; set; }

        [Required(ErrorMessage = "Please enter your email")]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter your password")]
        [Display(Name = "Password")]
        [StringLength(28, MinimumLength = 5, ErrorMessage = "Password should be at least 5 digits")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please enter your phone number")]
        [Display(Name = "Phone Number")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Phone number should be 10 digits")]
        public string Phone { get; set; }

        [HiddenInput(DisplayValue = false)]
        public double AdvanceMoney { get; set; }
    }
}

INTEX/Models/Report.cs
using System;
using INTEX.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace INTEX.Models
{
    public class Report
    {
        public DbSet<Compound> Compounds { get; set; }
        public DbSet<Assay> Assays { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
    }
}

INTEX/Controllers/CustomerController.cs
using INTEX.DAL;
using INTEX.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace INTEX.Controllers
{
    public class CustomerController : Controller
    {
        public static List<Customer> lsCustomers = new List<Customer>();

        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult CreateOrder()
        {
            return View();
        }

        public ActionResult Payment()
        {
            return View();
        }

        public ActionResult Report()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCustomer(Customer aCustomer)
        {

            if (ModelState.IsValid)
            {
                aCustomer.CustomerID = lsCustomers.Count() + 1;
                lsCustomers.Add(aCustomer);
                return RedirectToAction("Menu", "CustomerHome");
            }
            else
            {
                return View(aCustomer);
            }
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        public ActionResult Create(Customer aCustomer)
        {
            if (ModelState.IsValid)
            {
                aCustomer.CustomerID = lsCustomers.Count() + 1;
                lsCustomers.Add(aCustomer);
                return RedirectToAction("Login", "Customer");
            }
            else
            {
                return View(aCustomer);
            }
        }


        [HttpPost]
        public ActionResult Login(FormCollection form, bool rememberMe = false)
        {
            //String email = form["Email address"].ToString();
            //String password = form["Password"].ToString();

            //var db = new DBContext();
            //var currentUser = db.Database.SqlQuery<Customer>(
            //  "Select * " +
            //  "FROM Customer " +
            //  "WHERE Email = '" + email + "' AND " +
            //  "Password = '" + password + "'");

            //if (currentUser.Count() > 0)
            //{
            //    FormsAuthentication.SetAuthCookie(email, rememberMe);
            //    return RedirectToAction("Index", "Customer", new { userlogin = email });
            //}
            //else
            //{
            //    return View();
            //}

            return RedirectToAction("Index", "Customer");
        }

        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Customer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

INTEX/Controllers/OrderController.cs
using INTEX.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace INTEX.Controllers
{
    public class OrderController : Controller
    {

        public static List<Compound> lsCompounds = new List<Compound>();

        // GET: Order
        public ActionResult Index()
        {
            return View(lsCompounds);
        }

        // GET: Order/Details/5
        public ActionResult Details(string ltnum)
        {
            Compound oCompound = lsCompounds.Find(x => x.LTNumber == ltnum);
            return View(oCompound);
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Order/Create
        [HttpPost]
        public ActionResult Create(Compound aCompound)
        {
            if (ModelState.IsValid)
            {
                Random r = new Random();
                var x = r.Next(0, 1000000);
                string s = x.ToString("000000");

                aCompound.LTNumber = s;
                lsCompounds.Add(aCompound);
                return RedirectToAction("Index", "Customer", aCompound);
            }
            else
            {
                return View(aCompound);
            }
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Order/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

INTEX/Controllers/PaymentController.cs
using System;
using INTEX.DAL;
using INTEX.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace INTEX.Controllers
{
    public class PaymentController : Controller
    {

        DBContext db = new DBContext();

        // GET: Payment
        public ActionResult Index(Compound aCompound)
        {
            ViewBag.compoundName = aCompound.CompoundName;
            return View(aCompound);
        }

        // GET: Payment/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Payment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Payment/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Payment/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Payment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Payment/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Payment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

INTEX/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using INTEX.DAL;
using INTEX.Models;

namespace INTEX.Controllers
{
    public class ReportController : Controller
    {
        DBContext db = new DBContext();

        // GET: Report
        public ActionResult Index()
        {
            return View();
        }

        // GET: Report/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Report/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Report/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Report/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Report/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Report/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Report/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

INTEX/Views/Customer/Create.cshtml
@model INTEX.Models.Customer

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div id="register" class="form-horizontal">
    <div class="title">
        <h3>Register a New Account</h3>
    </div>
    <hr />
    <div>
        <button class="previous btn btn-primary">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn-primary", @style = "text-decoration: none; color: white" })
        </button>
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style="margin-top: 10px;">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control col-md-6" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-12" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control col-md-12" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <button class="btn btn-primary">
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn-primary", @style = "text-decoration: none; color: white" })
        </button>
        <button class="btn btn-success" type="submit">Register</button>
    </div>
</div>
}

<style>
    #register {
        width: 50%;
        margin: auto;
    }

        #register .title {
            text-align: center;
            margin: 3% auto;
        }
</style>

INTEX/Views/Customer/CreateOrder.cshtml
@model INTEX.Models.Compound

@{
    ViewBag.Title = "CreateOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div id="create-order" class="form-horizontal">
    <div class="title">
        <h4>Create a New Order</h4>
    </div>
    <hr />
    <div>
        <button class="btn btn-primary">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn-primary", @style = "text-decoration: none; color: white" })
        </button>
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CompoundName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CompoundName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CompoundName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MillQuant, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MillQuant, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MillQuant, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrderTotal, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrderTotal, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrderTotal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateArrived, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateArrived, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateArrived, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ReceivedBy, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReceivedBy, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ReceivedBy, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QuantitativeFileType, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QuantitativeFileType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QuantitativeFileType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QualitativeResults, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QualitativeResults, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QualitativeResults, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QuantitativeResults, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QuantitativeResults, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QuantitativeResults, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MTD, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MTD, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MTD, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-8" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button class="btn btn-success" type="submit">Create</button>
        </div>
    </div>
</div>
}

    <div>
        <button class="btn btn-primary">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn-primary", @style = "text-decoration: none; color: white" })
        </button>
    </div>

<style>
    .title {
        text-align: center;
        margin: 3% auto;
    }
    #create-order {
        width: 50%;
        margin: auto;
    }
</style>

INTEX/Views/Customer/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="menu">
    <div class="title">
        <h2>Hi XXX, so happy to see you again!</h2>
    </div>
    <div class="buttons">
        <button type="button" class="btn-lg btn">
            @Html.ActionLink("Create a New Order", "Create", "Order", new { area = "" }, new { @class = "btn btn-outline-primary btn-lg", @style = "text-decoration: none" })
        </button>
        <button type="button" class="btn-lg btn">
            @Html.ActionLink("Track Existing Orders", "Index", "Order", new { area = "" }, new { @class = "btn btn-outline-primary btn-lg", @style = "text-decoration: none" })
        </button>
        <button type="button" class="btn-lg btn">
            @Html.ActionLink("Order Status / Report", "Index", "Report", new { area = "" }, new { @class = "btn btn-outline-primary btn-lg", @style = "text-decoration: none" })
        </button>
        <button type="button" class="btn-lg btn">
            @Html.ActionLink("Manage My Payments", "Details", "Payment", new { area = "" }, new { @class = "btn btn-outline-primary btn-lg", @style = "text-decoration: none" })
        </button>
    </div>    
</div>


<style>
    .title {
        text-align: center;
        margin: 5% auto;
    }

    #menu {
        width: 50%;
        margin: auto;
    }

    .buttons {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        grid-gap: 35px;
    }

    .buttons .btn {
        height: 73px;
        width: 200px;
        text-align:center;
    }
</style>

INTEX/Views/Customer/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<div class="title">
    <h2>Log in</h2>
</div>

<div class="card">
    @using (Html.BeginForm("Login", "Customer", FormMethod.Post))
    {
        <div class="form-group">
            @Html.TextBox("Email address", null, new { @class="form-control", @placeholder = "Email"})
        </div>
        <div class="form-group">
            @Html.Password("Password", null, new { @class = "form-control", @placeholder = "Password" })
        </div>
        <div class="form-group">
            <div class="login">
                <button type="submit" class="btn btn-primary login-button">Login</button>
            </div>
            <span>Does not have an account? Register</span> @Html.ActionLink("Here", "Create", "Customer", new { area = "" }, new { @style = "font-size: 18px" })
        </div>
    }
</div>

<style>
    .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        width: 50%;
        height: 300px;
        margin: auto;
    }

        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }

    .title {
        text-align: center;
        margin: 3% auto;
    }

    .form-group {
        margin: auto;
        width: 50%;
    }

    .form-control {
        margin: 10% auto;
    }

    .login {
        display: flex;
        justify-content: center;
        margin: 3% auto;
    }

    .login-button {
        width: 50%;
    }
</style>

INTEX/Views/Customer/Report.cshtml
@{
    ViewBag.Title = "Report";
}

<h2>Report</h2>